spring:
  datasource:
    url: jdbc:postgresql://db:5432/prod_db
    username: postgres
    password: postgres
  liquibase:
    contexts: prod
  #    enabled: false
  jpa:
    properties:
      hibernate:
        search:
          backend:
            type: elasticsearch
            hosts: elasticsearch:9200
  data:
    redis:
      host: redis
