spring:
  profiles:
    default: dev

  #    active: prod

  application:
    name: micro-comments
  jpa:
    properties:
      hibernate:
        search:
          backend:
            type: elasticsearch
            hosts: localhost:9200
        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  port: 8082

#cache:
#  algorithm: LRU
#  capacity: 50

