spring:
  profiles:
    default: dev

#    active: prod

  application:
    name: micro-comments
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

server:
  port: 8082

micro-comments:
  openapi:
    dev-url: http://localhost:8082
    prod-url: micro-comments:8082

