spring:
  datasource:
    url: jdbc:postgresql://db:5432/prod_db
    username: postgres
    password: postgres
  liquibase:
    contexts: prod

  data:
    redis:
      host: redis

news-service:
  url:
    micro-news:8081